#!/bin/bash
apk add openjdk11
javaURL="${VulnerabilitiesURL}java/"
wget "${javaURL}Deserialization/deserialization.jar" -O Deserialization.jar 
mkdir -p /opt/dvd/code/java/
mv ./Deserialization.jar  /opt/dvd/code/java/Deserialization.jar  
